export default
[
    {
        "id": 1,
        "nombre": "Juan",
        "apellido": "Pérez",
        "telefono": "+123456789",
        "estado": "Estado1",
        "municipio": "Municipio1",
        "domicilio": "Calle 1, Ciudad1",
        "marca": "tp-link",
        "modelo": "tp-156",
        "producto": "Ups",
        "descripcionProblema": "no prende",
        "tipoServicios": "Reparacion"
    },
    {
        "id": 2,
        "nombre": "Ana",
        "apellido": "Garcia",
        "telefono": "+234567890",
        "estado": "Estado2",
        "municipio": "Municipio2",
        "domicilio": "Avenida 2, Ciudad2",
        "marca": "netgear",
        "modelo": "r6700",
        "producto": "Router",
        "descripcionProblema": "conexión lenta",
        "tipoServicios": "Mantenimiento"
    },
    {
        "id": 3,
        "nombre": "Carlos",
        "apellido": "Rodriguez",
        "telefono": "+345678901",
        "estado": "Estado3",
        "municipio": "Municipio3",
        "domicilio": "Boulevard 3, Ciudad3",
        "marca": "linksys",
        "modelo": "ea7500",
        "producto": "Switch",
        "descripcionProblema": "falla de red",
        "tipoServicios": "Reparacion"
    },
    {
        "id": 4,
        "nombre": "Maria",
        "apellido": "Lopez",
        "telefono": "+456789012",
        "estado": "Estado4",
        "municipio": "Municipio4",
        "domicilio": "Carretera 4, Ciudad4",
        "marca": "belkin",
        "modelo": "ac1200",
        "producto": "Modem",
        "descripcionProblema": "intermitente",
        "tipoServicios": "Mantenimiento"
    },
    {
        "id": 5,
        "nombre": "Pedro",
        "apellido": "Martinez",
        "telefono": "+567890123",
        "estado": "Estado5",
        "municipio": "Municipio5",
        "domicilio": "Autopista 5, Ciudad5",
        "marca": "d-link",
        "modelo": "dir-878",
        "producto": "Firewall",
        "descripcionProblema": "wifi débil",
        "tipoServicios": "Reparacion"
    },
    {
        "id": 6,
        "nombre": "Laura",
        "apellido": "Rojas",
        "telefono": "+678901234",
        "estado": "Estado6",
        "municipio": "Municipio6",
        "domicilio": "Calzada 6, Ciudad6",
        "marca": "asus",
        "modelo": "rt-ac66u",
        "producto": "Server",
        "descripcionProblema": "falla de hardware",
        "tipoServicios": "Mantenimiento"
    },
    {
        "id": 7,
        "nombre": "Sofia",
        "apellido": "Torres",
        "telefono": "+789012345",
        "estado": "Estado7",
        "municipio": "Municipio7",
        "domicilio": "Transversal 7, Ciudad7",
        "marca": "cisco",
        "modelo": "valet110n",
        "producto": "UPS",
        "descripcionProblema": "problemas de configuración",
        "tipoServicios": "Reparacion"
    },
    {
        "id": 8,
        "nombre": "Fernando",
        "apellido": "Morales",
        "telefono": "+890123456",
        "estado": "Estado8",
        "municipio": "Municipio8",
        "domicilio": "Intersección 8, Ciudad8",
        "marca": "tp-link",
        "modelo": "tl-wdr3600",
        "producto": "Router",
        "descripcionProblema": "falla de software",
        "tipoServicios": "Mantenimiento"
    },
    {
        "id": 9,
        "nombre": "Gabriela",
        "apellido": "Hernandez",
        "telefono": "+901234567",
        "estado": "Estado9",
        "municipio": "Municipio9",
        "domicilio": "Diagonal 9, Ciudad9",
        "marca": "netgear",
        "modelo": "r6900",
        "producto": "Switch",
        "descripcionProblema": "problemas de compatibilidad",
        "tipoServicios": "Reparacion"
    },
    {
        "id": 10,
        "nombre": "Jorge",
        "apellido": "Gomez",
        "telefono": "+012345678",
        "estado": "Estado10",
        "municipio": "Municipio10",
        "domicilio": "Circunvalación 10, Ciudad10",
        "marca": "linksys",
        "modelo": "ea7300",
        "producto": "Modem",
        "descripcionProblema": "falla de encendido",
        "tipoServicios": "Mantenimiento"
    }
]
